use rpython_span::Span;
use smol_str::SmolStr;

#[derive(Clone, Debug, PartialEq)]
pub struct SpannedToken {
    pub kind: TokenKind,
    pub span: Span,
}

#[derive(Clone, Debug, PartialEq)]
pub enum IntLiteral {
    Decimal(i64),
    Hex(i64),
    Bin(i64),
}

#[derive(Clone, Debug, PartialEq)]
pub enum TokenKind {
    Eof,
    Newline,
    Indent,
    Dedent,

    IntLit {
        value: IntLiteral,
    },
    FloatLit {
        value: f64,
    },
    StringLit {
        value: String,
    },
    BytesLit {
        value: Vec<u8>,
    },
    BoolLit(bool),

    Ident {
        name: SmolStr,
    },
    KwDef,
    KwClass,
    KwEnum,
    KwStruct,
    KwImpl,
    KwInterface,
    #[doc(hidden)]
    KwTrait, // deprecated alias; lexer maps "trait" here for compatibility
    KwIf,
    KwElif,
    KwElse,
    KwWhile,
    KwFor,
    KwLoop,
    KwBreak,
    KwContinue,
    KwReturn,
    KwPass,
    KwImport,
    KwFrom,
    KwAs,
    KwPub,
    KwMut,
    KwTrue,
    KwFalse,
    KwNone,
    KwSelf,
    KwIn,
    KwNot,
    KwAnd,
    KwOr,
    KwExtern,
    KwUnsafe,

    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    FloorDiv,
    Pow,
    EqEq,
    NotEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    Assign,
    Arrow,
    FatArrow,
    Colon,
    Semi,
    Comma,
    Dot,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    At,
    Amp,
    AmpMut,
    Pipe,
    Bang,
    Question,
    Underscore,
}

impl TokenKind {
    pub fn name(&self) -> &'static str {
        match self {
            Self::Eof => "Eof",
            Self::Newline => "Newline",
            Self::Indent => "Indent",
            Self::Dedent => "Dedent",
            Self::IntLit { .. } => "IntLit",
            Self::FloatLit { .. } => "FloatLit",
            Self::StringLit { .. } => "StringLit",
            Self::BytesLit { .. } => "BytesLit",
            Self::BoolLit(_) => "BoolLit",
            Self::Ident { .. } => "Ident",
            Self::KwDef => "KwDef",
            Self::KwClass => "KwClass",
            Self::KwEnum => "KwEnum",
            Self::KwStruct => "KwStruct",
            Self::KwImpl => "KwImpl",
            Self::KwInterface => "KwInterface",
            Self::KwTrait => "KwTrait",
            Self::KwIf => "KwIf",
            Self::KwElif => "KwElif",
            Self::KwElse => "KwElse",
            Self::KwWhile => "KwWhile",
            Self::KwFor => "KwFor",
            Self::KwLoop => "KwLoop",
            Self::KwBreak => "KwBreak",
            Self::KwContinue => "KwContinue",
            Self::KwReturn => "KwReturn",
            Self::KwPass => "KwPass",
            Self::KwImport => "KwImport",
            Self::KwFrom => "KwFrom",
            Self::KwAs => "KwAs",
            Self::KwPub => "KwPub",
            Self::KwMut => "KwMut",
            Self::KwTrue => "KwTrue",
            Self::KwFalse => "KwFalse",
            Self::KwNone => "KwNone",
            Self::KwSelf => "KwSelf",
            Self::KwIn => "KwIn",
            Self::KwNot => "KwNot",
            Self::KwAnd => "KwAnd",
            Self::KwOr => "KwOr",
            Self::KwExtern => "KwExtern",
            Self::KwUnsafe => "KwUnsafe",
            Self::Plus => "Plus",
            Self::Minus => "Minus",
            Self::Star => "Star",
            Self::Slash => "Slash",
            Self::Percent => "Percent",
            Self::FloorDiv => "FloorDiv",
            Self::Pow => "Pow",
            Self::EqEq => "EqEq",
            Self::NotEq => "NotEq",
            Self::Lt => "Lt",
            Self::LtEq => "LtEq",
            Self::Gt => "Gt",
            Self::GtEq => "GtEq",
            Self::Assign => "Assign",
            Self::Arrow => "Arrow",
            Self::FatArrow => "FatArrow",
            Self::Colon => "Colon",
            Self::Semi => "Semi",
            Self::Comma => "Comma",
            Self::Dot => "Dot",
            Self::LParen => "LParen",
            Self::RParen => "RParen",
            Self::LBracket => "LBracket",
            Self::RBracket => "RBracket",
            Self::LBrace => "LBrace",
            Self::RBrace => "RBrace",
            Self::At => "At",
            Self::Amp => "Amp",
            Self::AmpMut => "AmpMut",
            Self::Pipe => "Pipe",
            Self::Bang => "Bang",
            Self::Question => "Question",
            Self::Underscore => "Underscore",
        }
    }
}
